//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ftModel", "FK_teams_players_players", "player", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FT.Models.player), "teams_players", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FT.Models.teams_players), true)]
[assembly: EdmRelationshipAttribute("ftModel", "FK_teams_players_teams", "team", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FT.Models.team), "teams_players", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FT.Models.teams_players), true)]

#endregion

namespace FT.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ftEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ftEntities object using the connection string found in the 'ftEntities' section of the application configuration file.
        /// </summary>
        public ftEntities() : base("name=ftEntities", "ftEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ftEntities object.
        /// </summary>
        public ftEntities(string connectionString) : base(connectionString, "ftEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ftEntities object.
        /// </summary>
        public ftEntities(EntityConnection connection) : base(connection, "ftEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<player> players
        {
            get
            {
                if ((_players == null))
                {
                    _players = base.CreateObjectSet<player>("players");
                }
                return _players;
            }
        }
        private ObjectSet<player> _players;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<team> teams
        {
            get
            {
                if ((_teams == null))
                {
                    _teams = base.CreateObjectSet<team>("teams");
                }
                return _teams;
            }
        }
        private ObjectSet<team> _teams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<teams_players> teams_players
        {
            get
            {
                if ((_teams_players == null))
                {
                    _teams_players = base.CreateObjectSet<teams_players>("teams_players");
                }
                return _teams_players;
            }
        }
        private ObjectSet<teams_players> _teams_players;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the players EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToplayers(player player)
        {
            base.AddObject("players", player);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the teams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToteams(team team)
        {
            base.AddObject("teams", team);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the teams_players EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToteams_players(teams_players teams_players)
        {
            base.AddObject("teams_players", teams_players);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ftModel", Name="player")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class player : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new player object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static player Createplayer(global::System.Int32 id, global::System.String name)
        {
            player player = new player();
            player.Id = id;
            player.Name = name;
            return player;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK_teams_players_players", "teams_players")]
        public EntityCollection<teams_players> teams_players
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<teams_players>("ftModel.FK_teams_players_players", "teams_players");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<teams_players>("ftModel.FK_teams_players_players", "teams_players", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ftModel", Name="team")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class team : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new team object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static team Createteam(global::System.Int32 id, global::System.String name)
        {
            team team = new team();
            team.Id = id;
            team.Name = name;
            return team;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK_teams_players_teams", "teams_players")]
        public EntityCollection<teams_players> teams_players
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<teams_players>("ftModel.FK_teams_players_teams", "teams_players");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<teams_players>("ftModel.FK_teams_players_teams", "teams_players", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ftModel", Name="teams_players")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class teams_players : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new teams_players object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="teamId">Initial value of the TeamId property.</param>
        /// <param name="playersId">Initial value of the PlayersId property.</param>
        public static teams_players Createteams_players(global::System.Int32 id, global::System.Int32 teamId, global::System.Int32 playersId)
        {
            teams_players teams_players = new teams_players();
            teams_players.Id = id;
            teams_players.TeamId = teamId;
            teams_players.PlayersId = playersId;
            return teams_players;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TeamId
        {
            get
            {
                return _TeamId;
            }
            set
            {
                OnTeamIdChanging(value);
                ReportPropertyChanging("TeamId");
                _TeamId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TeamId");
                OnTeamIdChanged();
            }
        }
        private global::System.Int32 _TeamId;
        partial void OnTeamIdChanging(global::System.Int32 value);
        partial void OnTeamIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlayersId
        {
            get
            {
                return _PlayersId;
            }
            set
            {
                OnPlayersIdChanging(value);
                ReportPropertyChanging("PlayersId");
                _PlayersId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlayersId");
                OnPlayersIdChanged();
            }
        }
        private global::System.Int32 _PlayersId;
        partial void OnPlayersIdChanging(global::System.Int32 value);
        partial void OnPlayersIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK_teams_players_players", "player")]
        public player player
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<player>("ftModel.FK_teams_players_players", "player").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<player>("ftModel.FK_teams_players_players", "player").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<player> playerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<player>("ftModel.FK_teams_players_players", "player");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<player>("ftModel.FK_teams_players_players", "player", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK_teams_players_teams", "team")]
        public team team
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<team>("ftModel.FK_teams_players_teams", "team").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<team>("ftModel.FK_teams_players_teams", "team").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<team> teamReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<team>("ftModel.FK_teams_players_teams", "team");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<team>("ftModel.FK_teams_players_teams", "team", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
