//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ftModel", "FK__championship_matches_championships", "championship", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FT.Models.championship), "championship_matches", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FT.Models.championship_matches), true)]
[assembly: EdmRelationshipAttribute("ftModel", "FK__championship_matches_matches", "match", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FT.Models.match), "championship_matches", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FT.Models.championship_matches), true)]
[assembly: EdmRelationshipAttribute("ftModel", "FK__championship_teams_championship", "championship", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FT.Models.championship), "championship_teams", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FT.Models.championship_teams), true)]
[assembly: EdmRelationshipAttribute("ftModel", "FK_team_player_players", "player", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FT.Models.player), "team_player", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FT.Models.team_player), true)]
[assembly: EdmRelationshipAttribute("ftModel", "FK_team_player_teams", "team", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FT.Models.team), "team_player", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FT.Models.team_player), true)]
[assembly: EdmRelationshipAttribute("ftModel", "FK_gallery_gallery_items_galleries", "gallery", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FT.Models.gallery), "gallery_gallery_items", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FT.Models.gallery_gallery_items), true)]
[assembly: EdmRelationshipAttribute("ftModel", "FK_gallery_gallery_items_gallery_item", "gallery_item", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FT.Models.gallery_item), "gallery_gallery_items", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FT.Models.gallery_gallery_items), true)]

#endregion

namespace FT.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ftEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ftEntities object using the connection string found in the 'ftEntities' section of the application configuration file.
        /// </summary>
        public ftEntities() : base("name=ftEntities", "ftEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ftEntities object.
        /// </summary>
        public ftEntities(string connectionString) : base(connectionString, "ftEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ftEntities object.
        /// </summary>
        public ftEntities(EntityConnection connection) : base(connection, "ftEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<championship_matches> championship_matches
        {
            get
            {
                if ((_championship_matches == null))
                {
                    _championship_matches = base.CreateObjectSet<championship_matches>("championship_matches");
                }
                return _championship_matches;
            }
        }
        private ObjectSet<championship_matches> _championship_matches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<championship_teams> championship_teams
        {
            get
            {
                if ((_championship_teams == null))
                {
                    _championship_teams = base.CreateObjectSet<championship_teams>("championship_teams");
                }
                return _championship_teams;
            }
        }
        private ObjectSet<championship_teams> _championship_teams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<championship> championships
        {
            get
            {
                if ((_championships == null))
                {
                    _championships = base.CreateObjectSet<championship>("championships");
                }
                return _championships;
            }
        }
        private ObjectSet<championship> _championships;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<match_results> match_results
        {
            get
            {
                if ((_match_results == null))
                {
                    _match_results = base.CreateObjectSet<match_results>("match_results");
                }
                return _match_results;
            }
        }
        private ObjectSet<match_results> _match_results;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<match> matches
        {
            get
            {
                if ((_matches == null))
                {
                    _matches = base.CreateObjectSet<match>("matches");
                }
                return _matches;
            }
        }
        private ObjectSet<match> _matches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<player> players
        {
            get
            {
                if ((_players == null))
                {
                    _players = base.CreateObjectSet<player>("players");
                }
                return _players;
            }
        }
        private ObjectSet<player> _players;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<team_player> team_player
        {
            get
            {
                if ((_team_player == null))
                {
                    _team_player = base.CreateObjectSet<team_player>("team_player");
                }
                return _team_player;
            }
        }
        private ObjectSet<team_player> _team_player;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<team> teams
        {
            get
            {
                if ((_teams == null))
                {
                    _teams = base.CreateObjectSet<team>("teams");
                }
                return _teams;
            }
        }
        private ObjectSet<team> _teams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gallery> galleries
        {
            get
            {
                if ((_galleries == null))
                {
                    _galleries = base.CreateObjectSet<gallery>("galleries");
                }
                return _galleries;
            }
        }
        private ObjectSet<gallery> _galleries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gallery_gallery_items> gallery_gallery_items
        {
            get
            {
                if ((_gallery_gallery_items == null))
                {
                    _gallery_gallery_items = base.CreateObjectSet<gallery_gallery_items>("gallery_gallery_items");
                }
                return _gallery_gallery_items;
            }
        }
        private ObjectSet<gallery_gallery_items> _gallery_gallery_items;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gallery_item> gallery_item
        {
            get
            {
                if ((_gallery_item == null))
                {
                    _gallery_item = base.CreateObjectSet<gallery_item>("gallery_item");
                }
                return _gallery_item;
            }
        }
        private ObjectSet<gallery_item> _gallery_item;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the championship_matches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTochampionship_matches(championship_matches championship_matches)
        {
            base.AddObject("championship_matches", championship_matches);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the championship_teams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTochampionship_teams(championship_teams championship_teams)
        {
            base.AddObject("championship_teams", championship_teams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the championships EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTochampionships(championship championship)
        {
            base.AddObject("championships", championship);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the match_results EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomatch_results(match_results match_results)
        {
            base.AddObject("match_results", match_results);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the matches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomatches(match match)
        {
            base.AddObject("matches", match);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the players EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToplayers(player player)
        {
            base.AddObject("players", player);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the team_player EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToteam_player(team_player team_player)
        {
            base.AddObject("team_player", team_player);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the teams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToteams(team team)
        {
            base.AddObject("teams", team);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the galleries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogalleries(gallery gallery)
        {
            base.AddObject("galleries", gallery);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gallery_gallery_items EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogallery_gallery_items(gallery_gallery_items gallery_gallery_items)
        {
            base.AddObject("gallery_gallery_items", gallery_gallery_items);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gallery_item EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogallery_item(gallery_item gallery_item)
        {
            base.AddObject("gallery_item", gallery_item);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ftModel", Name="championship")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class championship : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new championship object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        public static championship Createchampionship(global::System.Int32 id, global::System.String name, global::System.String type)
        {
            championship championship = new championship();
            championship.Id = id;
            championship.Name = name;
            championship.Type = type;
            return championship;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> champion_Id
        {
            get
            {
                return _champion_Id;
            }
            set
            {
                Onchampion_IdChanging(value);
                ReportPropertyChanging("champion_Id");
                _champion_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("champion_Id");
                Onchampion_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _champion_Id;
        partial void Onchampion_IdChanging(Nullable<global::System.Int32> value);
        partial void Onchampion_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK__championship_matches_championships", "championship_matches")]
        public EntityCollection<championship_matches> championship_matches
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<championship_matches>("ftModel.FK__championship_matches_championships", "championship_matches");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<championship_matches>("ftModel.FK__championship_matches_championships", "championship_matches", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK__championship_teams_championship", "championship_teams")]
        public EntityCollection<championship_teams> championship_teams
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<championship_teams>("ftModel.FK__championship_teams_championship", "championship_teams");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<championship_teams>("ftModel.FK__championship_teams_championship", "championship_teams", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ftModel", Name="championship_matches")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class championship_matches : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new championship_matches object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="championship_Id">Initial value of the championship_Id property.</param>
        /// <param name="match_Id">Initial value of the match_Id property.</param>
        /// <param name="type">Initial value of the type property.</param>
        public static championship_matches Createchampionship_matches(global::System.Int32 id, global::System.Int32 championship_Id, global::System.Int32 match_Id, global::System.String type)
        {
            championship_matches championship_matches = new championship_matches();
            championship_matches.Id = id;
            championship_matches.championship_Id = championship_Id;
            championship_matches.match_Id = match_Id;
            championship_matches.type = type;
            return championship_matches;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 championship_Id
        {
            get
            {
                return _championship_Id;
            }
            set
            {
                Onchampionship_IdChanging(value);
                ReportPropertyChanging("championship_Id");
                _championship_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("championship_Id");
                Onchampionship_IdChanged();
            }
        }
        private global::System.Int32 _championship_Id;
        partial void Onchampionship_IdChanging(global::System.Int32 value);
        partial void Onchampionship_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 match_Id
        {
            get
            {
                return _match_Id;
            }
            set
            {
                Onmatch_IdChanging(value);
                ReportPropertyChanging("match_Id");
                _match_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("match_Id");
                Onmatch_IdChanged();
            }
        }
        private global::System.Int32 _match_Id;
        partial void Onmatch_IdChanging(global::System.Int32 value);
        partial void Onmatch_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK__championship_matches_championships", "championship")]
        public championship championship
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<championship>("ftModel.FK__championship_matches_championships", "championship").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<championship>("ftModel.FK__championship_matches_championships", "championship").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<championship> championshipReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<championship>("ftModel.FK__championship_matches_championships", "championship");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<championship>("ftModel.FK__championship_matches_championships", "championship", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK__championship_matches_matches", "match")]
        public match match
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<match>("ftModel.FK__championship_matches_matches", "match").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<match>("ftModel.FK__championship_matches_matches", "match").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<match> matchReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<match>("ftModel.FK__championship_matches_matches", "match");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<match>("ftModel.FK__championship_matches_matches", "match", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ftModel", Name="championship_teams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class championship_teams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new championship_teams object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="championship_Id">Initial value of the championship_Id property.</param>
        /// <param name="team_Id">Initial value of the team_Id property.</param>
        public static championship_teams Createchampionship_teams(global::System.Int32 id, global::System.Int32 championship_Id, global::System.Int32 team_Id)
        {
            championship_teams championship_teams = new championship_teams();
            championship_teams.Id = id;
            championship_teams.championship_Id = championship_Id;
            championship_teams.team_Id = team_Id;
            return championship_teams;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 championship_Id
        {
            get
            {
                return _championship_Id;
            }
            set
            {
                Onchampionship_IdChanging(value);
                ReportPropertyChanging("championship_Id");
                _championship_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("championship_Id");
                Onchampionship_IdChanged();
            }
        }
        private global::System.Int32 _championship_Id;
        partial void Onchampionship_IdChanging(global::System.Int32 value);
        partial void Onchampionship_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 team_Id
        {
            get
            {
                return _team_Id;
            }
            set
            {
                Onteam_IdChanging(value);
                ReportPropertyChanging("team_Id");
                _team_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("team_Id");
                Onteam_IdChanged();
            }
        }
        private global::System.Int32 _team_Id;
        partial void Onteam_IdChanging(global::System.Int32 value);
        partial void Onteam_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK__championship_teams_championship", "championship")]
        public championship championship
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<championship>("ftModel.FK__championship_teams_championship", "championship").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<championship>("ftModel.FK__championship_teams_championship", "championship").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<championship> championshipReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<championship>("ftModel.FK__championship_teams_championship", "championship");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<championship>("ftModel.FK__championship_teams_championship", "championship", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ftModel", Name="gallery")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gallery : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gallery object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="cover_Id">Initial value of the Cover_Id property.</param>
        public static gallery Creategallery(global::System.Int32 id, global::System.String name, global::System.Int32 cover_Id)
        {
            gallery gallery = new gallery();
            gallery.Id = id;
            gallery.Name = name;
            gallery.Cover_Id = cover_Id;
            return gallery;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cover_Id
        {
            get
            {
                return _Cover_Id;
            }
            set
            {
                OnCover_IdChanging(value);
                ReportPropertyChanging("Cover_Id");
                _Cover_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cover_Id");
                OnCover_IdChanged();
            }
        }
        private global::System.Int32 _Cover_Id;
        partial void OnCover_IdChanging(global::System.Int32 value);
        partial void OnCover_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK_gallery_gallery_items_galleries", "gallery_gallery_items")]
        public EntityCollection<gallery_gallery_items> gallery_gallery_items
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<gallery_gallery_items>("ftModel.FK_gallery_gallery_items_galleries", "gallery_gallery_items");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<gallery_gallery_items>("ftModel.FK_gallery_gallery_items_galleries", "gallery_gallery_items", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ftModel", Name="gallery_gallery_items")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gallery_gallery_items : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gallery_gallery_items object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="gallery_Id">Initial value of the gallery_Id property.</param>
        /// <param name="item_Id">Initial value of the item_Id property.</param>
        public static gallery_gallery_items Creategallery_gallery_items(global::System.Int32 id, global::System.Int32 gallery_Id, global::System.Int32 item_Id)
        {
            gallery_gallery_items gallery_gallery_items = new gallery_gallery_items();
            gallery_gallery_items.Id = id;
            gallery_gallery_items.gallery_Id = gallery_Id;
            gallery_gallery_items.item_Id = item_Id;
            return gallery_gallery_items;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 gallery_Id
        {
            get
            {
                return _gallery_Id;
            }
            set
            {
                Ongallery_IdChanging(value);
                ReportPropertyChanging("gallery_Id");
                _gallery_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gallery_Id");
                Ongallery_IdChanged();
            }
        }
        private global::System.Int32 _gallery_Id;
        partial void Ongallery_IdChanging(global::System.Int32 value);
        partial void Ongallery_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 item_Id
        {
            get
            {
                return _item_Id;
            }
            set
            {
                Onitem_IdChanging(value);
                ReportPropertyChanging("item_Id");
                _item_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("item_Id");
                Onitem_IdChanged();
            }
        }
        private global::System.Int32 _item_Id;
        partial void Onitem_IdChanging(global::System.Int32 value);
        partial void Onitem_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK_gallery_gallery_items_galleries", "gallery")]
        public gallery gallery
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gallery>("ftModel.FK_gallery_gallery_items_galleries", "gallery").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gallery>("ftModel.FK_gallery_gallery_items_galleries", "gallery").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<gallery> galleryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gallery>("ftModel.FK_gallery_gallery_items_galleries", "gallery");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<gallery>("ftModel.FK_gallery_gallery_items_galleries", "gallery", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK_gallery_gallery_items_gallery_item", "gallery_item")]
        public gallery_item gallery_item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gallery_item>("ftModel.FK_gallery_gallery_items_gallery_item", "gallery_item").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gallery_item>("ftModel.FK_gallery_gallery_items_gallery_item", "gallery_item").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<gallery_item> gallery_itemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<gallery_item>("ftModel.FK_gallery_gallery_items_gallery_item", "gallery_item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<gallery_item>("ftModel.FK_gallery_gallery_items_gallery_item", "gallery_item", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ftModel", Name="gallery_item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gallery_item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gallery_item object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        public static gallery_item Creategallery_item(global::System.Int32 id, global::System.String type, global::System.String url)
        {
            gallery_item gallery_item = new gallery_item();
            gallery_item.Id = id;
            gallery_item.Type = type;
            gallery_item.Url = url;
            return gallery_item;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK_gallery_gallery_items_gallery_item", "gallery_gallery_items")]
        public EntityCollection<gallery_gallery_items> gallery_gallery_items
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<gallery_gallery_items>("ftModel.FK_gallery_gallery_items_gallery_item", "gallery_gallery_items");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<gallery_gallery_items>("ftModel.FK_gallery_gallery_items_gallery_item", "gallery_gallery_items", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ftModel", Name="match")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class match : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new match object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="team_b_Id">Initial value of the team_b_Id property.</param>
        /// <param name="team_a_Id">Initial value of the team_a_Id property.</param>
        public static match Creatematch(global::System.Int32 id, global::System.Int32 team_b_Id, global::System.Int32 team_a_Id)
        {
            match match = new match();
            match.Id = id;
            match.team_b_Id = team_b_Id;
            match.team_a_Id = team_a_Id;
            return match;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 team_b_Id
        {
            get
            {
                return _team_b_Id;
            }
            set
            {
                Onteam_b_IdChanging(value);
                ReportPropertyChanging("team_b_Id");
                _team_b_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("team_b_Id");
                Onteam_b_IdChanged();
            }
        }
        private global::System.Int32 _team_b_Id;
        partial void Onteam_b_IdChanging(global::System.Int32 value);
        partial void Onteam_b_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 team_a_Id
        {
            get
            {
                return _team_a_Id;
            }
            set
            {
                Onteam_a_IdChanging(value);
                ReportPropertyChanging("team_a_Id");
                _team_a_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("team_a_Id");
                Onteam_a_IdChanged();
            }
        }
        private global::System.Int32 _team_a_Id;
        partial void Onteam_a_IdChanging(global::System.Int32 value);
        partial void Onteam_a_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK__championship_matches_matches", "championship_matches")]
        public EntityCollection<championship_matches> championship_matches
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<championship_matches>("ftModel.FK__championship_matches_matches", "championship_matches");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<championship_matches>("ftModel.FK__championship_matches_matches", "championship_matches", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ftModel", Name="match_results")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class match_results : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new match_results object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="match_Id">Initial value of the match_Id property.</param>
        /// <param name="set">Initial value of the Set property.</param>
        /// <param name="team_a_games">Initial value of the team_a_games property.</param>
        /// <param name="team_b_games">Initial value of the team_b_games property.</param>
        public static match_results Creatematch_results(global::System.Int32 id, global::System.Int32 match_Id, global::System.Int32 set, global::System.Int32 team_a_games, global::System.Int32 team_b_games)
        {
            match_results match_results = new match_results();
            match_results.Id = id;
            match_results.match_Id = match_Id;
            match_results.Set = set;
            match_results.team_a_games = team_a_games;
            match_results.team_b_games = team_b_games;
            return match_results;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 match_Id
        {
            get
            {
                return _match_Id;
            }
            set
            {
                Onmatch_IdChanging(value);
                ReportPropertyChanging("match_Id");
                _match_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("match_Id");
                Onmatch_IdChanged();
            }
        }
        private global::System.Int32 _match_Id;
        partial void Onmatch_IdChanging(global::System.Int32 value);
        partial void Onmatch_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Set
        {
            get
            {
                return _Set;
            }
            set
            {
                OnSetChanging(value);
                ReportPropertyChanging("Set");
                _Set = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Set");
                OnSetChanged();
            }
        }
        private global::System.Int32 _Set;
        partial void OnSetChanging(global::System.Int32 value);
        partial void OnSetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 team_a_games
        {
            get
            {
                return _team_a_games;
            }
            set
            {
                Onteam_a_gamesChanging(value);
                ReportPropertyChanging("team_a_games");
                _team_a_games = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("team_a_games");
                Onteam_a_gamesChanged();
            }
        }
        private global::System.Int32 _team_a_games;
        partial void Onteam_a_gamesChanging(global::System.Int32 value);
        partial void Onteam_a_gamesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 team_b_games
        {
            get
            {
                return _team_b_games;
            }
            set
            {
                Onteam_b_gamesChanging(value);
                ReportPropertyChanging("team_b_games");
                _team_b_games = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("team_b_games");
                Onteam_b_gamesChanged();
            }
        }
        private global::System.Int32 _team_b_games;
        partial void Onteam_b_gamesChanging(global::System.Int32 value);
        partial void Onteam_b_gamesChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ftModel", Name="player")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class player : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new player object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static player Createplayer(global::System.Int32 id, global::System.String name)
        {
            player player = new player();
            player.Id = id;
            player.Name = name;
            return player;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Image
        {
            get
            {
                return _Image;
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.String _Image;
        partial void OnImageChanging(global::System.String value);
        partial void OnImageChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK_team_player_players", "team_player")]
        public EntityCollection<team_player> team_player
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<team_player>("ftModel.FK_team_player_players", "team_player");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<team_player>("ftModel.FK_team_player_players", "team_player", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ftModel", Name="team")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class team : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new team object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static team Createteam(global::System.Int32 id, global::System.String name)
        {
            team team = new team();
            team.Id = id;
            team.Name = name;
            return team;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Logo
        {
            get
            {
                return _Logo;
            }
            set
            {
                OnLogoChanging(value);
                ReportPropertyChanging("Logo");
                _Logo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Logo");
                OnLogoChanged();
            }
        }
        private global::System.String _Logo;
        partial void OnLogoChanging(global::System.String value);
        partial void OnLogoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK_team_player_teams", "team_player")]
        public EntityCollection<team_player> team_player
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<team_player>("ftModel.FK_team_player_teams", "team_player");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<team_player>("ftModel.FK_team_player_teams", "team_player", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ftModel", Name="team_player")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class team_player : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new team_player object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="team_Id">Initial value of the Team_Id property.</param>
        /// <param name="player_Id">Initial value of the Player_Id property.</param>
        public static team_player Createteam_player(global::System.Int32 id, global::System.Int32 team_Id, global::System.Int32 player_Id)
        {
            team_player team_player = new team_player();
            team_player.Id = id;
            team_player.Team_Id = team_Id;
            team_player.Player_Id = player_Id;
            return team_player;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Team_Id
        {
            get
            {
                return _Team_Id;
            }
            set
            {
                OnTeam_IdChanging(value);
                ReportPropertyChanging("Team_Id");
                _Team_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Team_Id");
                OnTeam_IdChanged();
            }
        }
        private global::System.Int32 _Team_Id;
        partial void OnTeam_IdChanging(global::System.Int32 value);
        partial void OnTeam_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Player_Id
        {
            get
            {
                return _Player_Id;
            }
            set
            {
                OnPlayer_IdChanging(value);
                ReportPropertyChanging("Player_Id");
                _Player_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Player_Id");
                OnPlayer_IdChanged();
            }
        }
        private global::System.Int32 _Player_Id;
        partial void OnPlayer_IdChanging(global::System.Int32 value);
        partial void OnPlayer_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK_team_player_players", "player")]
        public player player
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<player>("ftModel.FK_team_player_players", "player").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<player>("ftModel.FK_team_player_players", "player").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<player> playerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<player>("ftModel.FK_team_player_players", "player");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<player>("ftModel.FK_team_player_players", "player", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ftModel", "FK_team_player_teams", "team")]
        public team team
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<team>("ftModel.FK_team_player_teams", "team").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<team>("ftModel.FK_team_player_teams", "team").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<team> teamReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<team>("ftModel.FK_team_player_teams", "team");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<team>("ftModel.FK_team_player_teams", "team", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
